apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dac0joytk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dac0joytk-java-quarkus-gitops